/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ImproveYourSentencePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  provider: "gemini",
  openAiApiKey: "",
  geminiApiKey: "",
  openRouterApiKey: "",
  openAiModel: "gpt-4o",
  geminiModel: "gemini-1.5-flash",
  openRouterModel: "openai/gpt-4o",
  systemPrompt: `Analyze the following sentence.
Provide the syntactically correct and natural version of the sentence.
Then, provide 3 alternative versions (e.g., more professional, creative, or concise).
Format your response using Markdown, starting with "## Corrected Version:", followed by "## Alternatives:", and present the alternatives as a numbered list.
Output nothing else.`
};
var ImproveYourSentenceSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Improve Your Sentence Settings" });
    new import_obsidian.Setting(containerEl).setName("AI Provider").setDesc("Select the AI provider to use for generating sentence improvements.").addDropdown(
      (dropdown) => dropdown.addOption("openai", "OpenAI (ChatGPT)").addOption("gemini", "Google Gemini").addOption("openrouter", "OpenRouter").setValue(this.plugin.settings.provider).onChange(async (value) => {
        this.plugin.settings.provider = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.provider === "openai") {
      new import_obsidian.Setting(containerEl).setName("OpenAI API Key").setDesc("Enter your OpenAI API secret key.").addText(
        (text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.openAiApiKey).onChange(async (value) => {
          this.plugin.settings.openAiApiKey = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian.Setting(containerEl).setName("OpenAI Model").setDesc("Enter the OpenAI model ID (e.g., gpt-4o, gpt-3.5-turbo).").addText(
        (text) => text.setPlaceholder("gpt-4o").setValue(this.plugin.settings.openAiModel).onChange(async (value) => {
          this.plugin.settings.openAiModel = value;
          await this.plugin.saveSettings();
        })
      );
    } else if (this.plugin.settings.provider === "gemini") {
      new import_obsidian.Setting(containerEl).setName("Gemini API Key").setDesc("Enter your Google Gemini API key.").addText(
        (text) => text.setPlaceholder("AIzaSy...").setValue(this.plugin.settings.geminiApiKey).onChange(async (value) => {
          this.plugin.settings.geminiApiKey = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian.Setting(containerEl).setName("Gemini Model").setDesc("Enter the Gemini model ID (e.g., gemini-1.5-flash, gemini-1.5-pro).").addText(
        (text) => text.setPlaceholder("gemini-1.5-flash").setValue(this.plugin.settings.geminiModel).onChange(async (value) => {
          this.plugin.settings.geminiModel = value;
          await this.plugin.saveSettings();
        })
      );
    } else if (this.plugin.settings.provider === "openrouter") {
      new import_obsidian.Setting(containerEl).setName("OpenRouter API Key").setDesc("Enter your OpenRouter API key.").addText(
        (text) => text.setPlaceholder("sk-or-...").setValue(this.plugin.settings.openRouterApiKey).onChange(async (value) => {
          this.plugin.settings.openRouterApiKey = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian.Setting(containerEl).setName("OpenRouter Model").setDesc("Enter the OpenRouter model ID (e.g., openai/gpt-4o, anthropic/claude-3-sonnet).").addText(
        (text) => text.setPlaceholder("openai/gpt-4o").setValue(this.plugin.settings.openRouterModel).onChange(async (value) => {
          this.plugin.settings.openRouterModel = value;
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian.Setting(containerEl).setName("System Prompt").setDesc("Customize how the AI should respond to the sentence selection.").addTextArea(
      (text) => text.setPlaceholder("Enter system prompt...").setValue(this.plugin.settings.systemPrompt).onChange(async (value) => {
        this.plugin.settings.systemPrompt = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/ImproveSentenceView.ts
var import_obsidian2 = require("obsidian");

// src/api.ts
async function* streamAIResponse(messages, settings) {
  const { provider, openAiApiKey, geminiApiKey, openRouterApiKey } = settings;
  try {
    if (provider === "gemini") {
      yield* streamGemini(messages, geminiApiKey, settings.geminiModel);
    } else if (provider === "openai") {
      yield* streamOpenAI(messages, openAiApiKey, settings.openAiModel);
    } else if (provider === "openrouter") {
      yield* streamOpenRouter(messages, openRouterApiKey, settings.openRouterModel);
    } else {
      throw new Error("Unknown AI provider configured.");
    }
  } catch (e) {
    console.error("AI stream error:", e);
    yield `

**Error**: ${e.message || "An unknown error occurred during AI completion."}`;
  }
}
async function* streamOpenAI(messages, apiKey, model) {
  if (!apiKey)
    throw new Error("OpenAI API key is missing. Please set it in the plugin settings.");
  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model,
      messages,
      stream: true
    })
  });
  yield* parseSSE(response);
}
async function* streamOpenRouter(messages, apiKey, model) {
  if (!apiKey)
    throw new Error("OpenRouter API key is missing. Please set it in the plugin settings.");
  const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${apiKey}`,
      "HTTP-Referer": "https://obsidian.md"
      // Required by OpenRouter sometimes
    },
    body: JSON.stringify({
      model,
      messages,
      stream: true
    })
  });
  yield* parseSSE(response);
}
async function* parseSSE(response) {
  var _a, _b, _c, _d;
  if (!response.ok) {
    const text = await response.text();
    throw new Error(`HTTP Error ${response.status}: ${text}`);
  }
  const reader = (_a = response.body) == null ? void 0 : _a.getReader();
  const decoder = new TextDecoder();
  if (!reader)
    throw new Error("Could not read response stream");
  while (true) {
    const { done, value } = await reader.read();
    if (done)
      break;
    const chunk = decoder.decode(value, { stream: true });
    const lines = chunk.split("\n");
    for (const line of lines) {
      if (line.trim().startsWith("data: ")) {
        const data = line.trim().slice(6);
        if (data === "[DONE]")
          continue;
        try {
          const parsed = JSON.parse(data);
          if ((_d = (_c = (_b = parsed.choices) == null ? void 0 : _b[0]) == null ? void 0 : _c.delta) == null ? void 0 : _d.content) {
            yield parsed.choices[0].delta.content;
          }
        } catch (e) {
        }
      }
    }
  }
}
async function* streamGemini(messages, apiKey, model) {
  var _a, _b, _c, _d, _e, _f;
  if (!apiKey)
    throw new Error("Gemini API key is missing. Please set it in the plugin settings.");
  const systemMessage = messages.find((m) => m.role === "system");
  const standardMessages = messages.filter((m) => m.role !== "system");
  const contents = standardMessages.map((msg) => ({
    role: msg.role === "assistant" ? "model" : "user",
    parts: [{ text: msg.content }]
  }));
  const body = { contents };
  if (systemMessage) {
    body.systemInstruction = {
      parts: [{ text: systemMessage.content }]
    };
  }
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:streamGenerateContent?alt=sse&key=${apiKey}`;
  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify(body)
  });
  if (!response.ok) {
    const text = await response.text();
    throw new Error(`HTTP Error ${response.status}: ${text}`);
  }
  const reader = (_a = response.body) == null ? void 0 : _a.getReader();
  const decoder = new TextDecoder();
  if (!reader)
    throw new Error("Could not read response stream");
  while (true) {
    const { done, value } = await reader.read();
    if (done)
      break;
    const chunk = decoder.decode(value, { stream: true });
    const lines = chunk.split("\n");
    for (const line of lines) {
      if (line.trim().startsWith("data: ")) {
        const data = line.trim().slice(6);
        if (data === "[DONE]")
          continue;
        try {
          const parsed = JSON.parse(data);
          if ((_f = (_e = (_d = (_c = (_b = parsed.candidates) == null ? void 0 : _b[0]) == null ? void 0 : _c.content) == null ? void 0 : _d.parts) == null ? void 0 : _e[0]) == null ? void 0 : _f.text) {
            yield parsed.candidates[0].content.parts[0].text;
          }
        } catch (e) {
        }
      }
    }
  }
}

// src/ImproveSentenceView.ts
var IMPROVE_SENTENCE_VIEW_TYPE = "improve-sentence-view";
var ImproveSentenceView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.messages = [];
    this.plugin = plugin;
  }
  getViewType() {
    return IMPROVE_SENTENCE_VIEW_TYPE;
  }
  getDisplayText() {
    return "Improve Sentence Chat";
  }
  getIcon() {
    return "message-square";
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("improve-sentence-view-container");
    const header = contentEl.createDiv({ cls: "sidebar-header" });
    header.createEl("h4", { text: "AI Chat" });
    const refreshBtn = header.createDiv({ cls: "refresh-icon" });
    (0, import_obsidian2.setIcon)(refreshBtn, "rotate-ccw");
    refreshBtn.setAttribute("aria-label", "Clear history");
    refreshBtn.addEventListener("click", () => this.clearHistory());
    this.chatContainer = contentEl.createDiv({ cls: "chat-container sidebar" });
    const inputContainer = contentEl.createDiv({ cls: "chat-input-container sidebar" });
    this.inputEl = inputContainer.createEl("textarea", { cls: "chat-input" });
    this.inputEl.placeholder = "Type to chat...";
    this.inputEl.rows = 2;
    this.sendButton = inputContainer.createEl("button", { text: "Send", cls: "chat-send-btn" });
    this.sendButton.addEventListener("click", () => this.sendMessage());
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.sendMessage();
      }
    });
    if (this.messages.length === 0) {
      this.messages.push({ role: "system", content: this.plugin.settings.systemPrompt });
    }
  }
  async sendMessage() {
    const text = this.inputEl.value.trim();
    if (!text)
      return;
    this.inputEl.value = "";
    this.messages.push({ role: "user", content: text });
    this.renderUserMessage(text);
    await this.generateAssistantResponse();
  }
  async generateAssistantResponse() {
    const assistantMessageIdx = this.messages.length;
    this.messages.push({ role: "assistant", content: "" });
    const bubble = this.createMessageBubble("assistant");
    this.inputEl.disabled = true;
    this.sendButton.disabled = true;
    try {
      const stream = streamAIResponse(this.messages.slice(0, -1), this.plugin.settings);
      let content = "";
      for await (const chunk of stream) {
        content += chunk;
        bubble.innerText = content;
        this.chatContainer.scrollTop = this.chatContainer.scrollHeight;
      }
      this.messages[assistantMessageIdx].content = content;
      bubble.empty();
      await import_obsidian2.MarkdownRenderer.renderMarkdown(content, bubble, "", this.plugin);
    } catch (e) {
      bubble.innerText += `
Error: ${e.toString()}`;
    } finally {
      this.inputEl.disabled = false;
      this.sendButton.disabled = false;
      this.inputEl.focus();
      this.chatContainer.scrollTop = this.chatContainer.scrollHeight;
    }
  }
  renderUserMessage(content) {
    const bubble = this.createMessageBubble("user");
    bubble.innerText = content;
    this.chatContainer.scrollTop = this.chatContainer.scrollHeight;
  }
  createMessageBubble(role) {
    const wrapper = this.chatContainer.createDiv({ cls: `chat-message ${role}` });
    const bubble = wrapper.createDiv({ cls: "bubble" });
    return bubble;
  }
  async clearHistory() {
    this.messages = [];
    this.messages.push({ role: "system", content: this.plugin.settings.systemPrompt });
    this.chatContainer.empty();
  }
  async setMessages(messages) {
    this.messages = [...messages];
    this.chatContainer.empty();
    for (const msg of this.messages) {
      if (msg.role === "system")
        continue;
      const bubble = this.createMessageBubble(msg.role);
      await import_obsidian2.MarkdownRenderer.renderMarkdown(msg.content, bubble, "", this.plugin);
    }
    this.chatContainer.scrollTop = this.chatContainer.scrollHeight;
  }
  async startImprovement(sentence) {
    this.messages = [];
    this.messages.push({ role: "system", content: this.plugin.settings.systemPrompt });
    this.messages.push({ role: "user", content: `Please improve this sentence:

"${sentence}"` });
    this.chatContainer.empty();
    this.renderUserMessage(`Improve this: "${sentence}"`);
    await this.generateAssistantResponse();
  }
};

// src/main.ts
var ImproveYourSentencePlugin = class extends import_obsidian3.Plugin {
  async onload() {
    console.log("loading improve your sentence plugin");
    await this.loadSettings();
    this.registerView(
      IMPROVE_SENTENCE_VIEW_TYPE,
      (leaf) => new ImproveSentenceView(leaf, this)
    );
    this.addRibbonIcon("message-square", "Open Improve Sentence Chat", () => {
      this.activateView();
    });
    this.addCommand({
      id: "improve-selected-sentence",
      name: "Improve Selected Sentence",
      editorCallback: (editor, view) => {
        const selection = editor.getSelection();
        if (selection.trim() === "") {
          return;
        }
        this.activateView().then((v) => {
          if (v) {
            v.startImprovement(selection);
          }
        });
      }
    });
    this.addCommand({
      id: "open-improve-sentence-sidebar",
      name: "Open Sidebar Chat",
      callback: () => {
        this.activateView();
      }
    });
    this.addSettingTab(new ImproveYourSentenceSettingTab(this.app, this));
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(IMPROVE_SENTENCE_VIEW_TYPE)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (!rightLeaf)
        return null;
      leaf = rightLeaf;
      await leaf.setViewState({
        type: IMPROVE_SENTENCE_VIEW_TYPE,
        active: true
      });
    }
    workspace.revealLeaf(leaf);
    return leaf.view;
  }
  onunload() {
    console.log("unloading improve your sentence plugin");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
