/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ImproveYourSentencePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  provider: "gemini",
  openAiApiKey: "",
  geminiApiKey: "",
  openRouterApiKey: "",
  openAiModel: "gpt-4o",
  geminiModel: "gemini-1.5-flash",
  openRouterModel: "openai/gpt-4o",
  customPrompts: [
    {
      id: "improve-sentence",
      name: "Improve Sentence",
      prompt: `Analyze the following sentence.
Provide the syntactically correct and natural version of the sentence.
Then, provide 3 alternative versions (e.g., more professional, creative, or concise).
Format your response using Markdown, starting with "## Corrected Version:", followed by "## Alternatives:", and present the alternatives as a numbered list.
Output nothing else.`
    },
    {
      id: "check-grammar",
      name: "Check Grammar",
      prompt: "Check the grammar and spelling of the following text. Provide the corrected version and a brief explanation of the changes."
    },
    {
      id: "translate-to-vn",
      name: "Translate to Vietnamese",
      prompt: "Translate the following text to Vietnamese."
    }
  ],
  vocabulary: []
};
var ImproveYourSentenceSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.vocabPage = 0;
    this.vocabPageSize = 10;
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Improve Your Sentence Settings" });
    new import_obsidian.Setting(containerEl).setName("AI Provider").setDesc("Select the AI provider to use for generating sentence improvements.").addDropdown(
      (dropdown) => dropdown.addOption("openai", "OpenAI (ChatGPT)").addOption("gemini", "Google Gemini").addOption("openrouter", "OpenRouter").setValue(this.plugin.settings.provider).onChange(async (value) => {
        this.plugin.settings.provider = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.provider === "openai") {
      new import_obsidian.Setting(containerEl).setName("OpenAI API Key").setDesc("Enter your OpenAI API secret key.").addText(
        (text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.openAiApiKey).onChange(async (value) => {
          this.plugin.settings.openAiApiKey = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian.Setting(containerEl).setName("OpenAI Model").setDesc("Enter the OpenAI model ID (e.g., gpt-4o, gpt-3.5-turbo).").addText(
        (text) => text.setPlaceholder("gpt-4o").setValue(this.plugin.settings.openAiModel).onChange(async (value) => {
          this.plugin.settings.openAiModel = value;
          await this.plugin.saveSettings();
        })
      );
    } else if (this.plugin.settings.provider === "gemini") {
      new import_obsidian.Setting(containerEl).setName("Gemini API Key").setDesc("Enter your Google Gemini API key.").addText(
        (text) => text.setPlaceholder("AIzaSy...").setValue(this.plugin.settings.geminiApiKey).onChange(async (value) => {
          this.plugin.settings.geminiApiKey = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian.Setting(containerEl).setName("Gemini Model").setDesc("Enter the Gemini model ID (e.g., gemini-1.5-flash, gemini-1.5-pro).").addText(
        (text) => text.setPlaceholder("gemini-1.5-flash").setValue(this.plugin.settings.geminiModel).onChange(async (value) => {
          this.plugin.settings.geminiModel = value;
          await this.plugin.saveSettings();
        })
      );
    } else if (this.plugin.settings.provider === "openrouter") {
      new import_obsidian.Setting(containerEl).setName("OpenRouter API Key").setDesc("Enter your OpenRouter API key.").addText(
        (text) => text.setPlaceholder("sk-or-...").setValue(this.plugin.settings.openRouterApiKey).onChange(async (value) => {
          this.plugin.settings.openRouterApiKey = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian.Setting(containerEl).setName("OpenRouter Model").setDesc("Enter the OpenRouter model ID (e.g., openai/gpt-4o, anthropic/claude-3-sonnet).").addText(
        (text) => text.setPlaceholder("openai/gpt-4o").setValue(this.plugin.settings.openRouterModel).onChange(async (value) => {
          this.plugin.settings.openRouterModel = value;
          await this.plugin.saveSettings();
        })
      );
    }
    containerEl.createEl("h3", { text: "Custom Prompts" });
    this.plugin.settings.customPrompts.forEach((prompt, index) => {
      const s = new import_obsidian.Setting(containerEl).setName(`Prompt ${index + 1}: ${prompt.name}`).setDesc("Description: " + (prompt.prompt.length > 50 ? prompt.prompt.substring(0, 50) + "..." : prompt.prompt));
      s.addText(
        (text) => text.setPlaceholder("Prompt Name").setValue(prompt.name).onChange(async (value) => {
          prompt.name = value;
          await this.plugin.saveSettings();
        })
      );
      s.addExtraButton((cb) => {
        cb.setIcon("trash").setTooltip("Delete Prompt").onClick(async () => {
          this.plugin.settings.customPrompts.splice(index, 1);
          await this.plugin.saveSettings();
          this.display();
        });
      });
      new import_obsidian.Setting(containerEl).setName("Prompt Content").setDesc("The actual prompt sent to the AI.").addTextArea(
        (text) => text.setPlaceholder("Enter system prompt...").setValue(prompt.prompt).onChange(async (value) => {
          prompt.prompt = value;
          await this.plugin.saveSettings();
        })
      );
    });
    new import_obsidian.Setting(containerEl).addButton(
      (btn) => btn.setButtonText("Add New Prompt").setCta().onClick(async () => {
        this.plugin.settings.customPrompts.push({
          id: "custom-prompt-" + Date.now(),
          name: "New Prompt",
          prompt: ""
        });
        await this.plugin.saveSettings();
        this.display();
      })
    );
    containerEl.createEl("h3", { text: "Vocabulary Management" });
    if (this.plugin.settings.vocabulary.length === 0) {
      containerEl.createEl("p", { text: "No vocabulary words saved yet.", cls: "setting-item-description" });
    } else {
      const tableWrapper = containerEl.createDiv({ cls: "vocab-table-wrapper" });
      const table = tableWrapper.createEl("table", { cls: "vocab-table" });
      const header = table.createEl("thead").createEl("tr");
      header.createEl("th", { text: "Word" });
      header.createEl("th", { text: "Added" });
      header.createEl("th", { text: "Next Review" });
      header.createEl("th", { text: "Actions" });
      const tbody = table.createEl("tbody");
      const sortedVocab = [...this.plugin.settings.vocabulary].sort((a, b) => a.nextReview - b.nextReview);
      const start = this.vocabPage * this.vocabPageSize;
      const end = start + this.vocabPageSize;
      const pagedVocab = sortedVocab.slice(start, end);
      pagedVocab.forEach((item) => {
        const row = tbody.createEl("tr");
        row.createEl("td", { text: item.word });
        row.createEl("td", { text: new Date(item.dateAdded).toLocaleDateString() });
        row.createEl("td", { text: new Date(item.nextReview).toLocaleDateString() });
        const actionsCell = row.createEl("td");
        const deleteBtn = actionsCell.createEl("button", { cls: "vocab-delete-btn" });
        (0, import_obsidian.setIcon)(deleteBtn, "trash");
        deleteBtn.addEventListener("click", async () => {
          this.plugin.settings.vocabulary = this.plugin.settings.vocabulary.filter((v) => v !== item);
          await this.plugin.saveSettings();
          this.display();
        });
      });
      const pagination = containerEl.createDiv({ cls: "vocab-pagination" });
      const totalPages = Math.ceil(sortedVocab.length / this.vocabPageSize);
      const prevBtn = pagination.createEl("button", { text: "Previous", cls: "vocab-page-btn" });
      if (this.vocabPage === 0)
        prevBtn.disabled = true;
      prevBtn.addEventListener("click", () => {
        this.vocabPage--;
        this.display();
      });
      pagination.createSpan({ text: ` Page ${this.vocabPage + 1} of ${totalPages} `, cls: "vocab-page-info" });
      const nextBtn = pagination.createEl("button", { text: "Next", cls: "vocab-page-btn" });
      if (this.vocabPage >= totalPages - 1)
        nextBtn.disabled = true;
      nextBtn.addEventListener("click", () => {
        this.vocabPage++;
        this.display();
      });
    }
  }
};

// src/ImproveSentenceView.ts
var import_obsidian2 = require("obsidian");

// src/api.ts
async function* streamAIResponse(messages, settings) {
  const { provider, openAiApiKey, geminiApiKey, openRouterApiKey } = settings;
  try {
    if (provider === "gemini") {
      yield* streamGemini(messages, geminiApiKey, settings.geminiModel);
    } else if (provider === "openai") {
      yield* streamOpenAI(messages, openAiApiKey, settings.openAiModel);
    } else if (provider === "openrouter") {
      yield* streamOpenRouter(messages, openRouterApiKey, settings.openRouterModel);
    } else {
      throw new Error("Unknown AI provider configured.");
    }
  } catch (e) {
    console.error("AI stream error:", e);
    yield `

**Error**: ${e.message || "An unknown error occurred during AI completion."}`;
  }
}
async function* streamOpenAI(messages, apiKey, model) {
  if (!apiKey)
    throw new Error("OpenAI API key is missing. Please set it in the plugin settings.");
  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model,
      messages,
      stream: true
    })
  });
  yield* parseSSE(response);
}
async function* streamOpenRouter(messages, apiKey, model) {
  if (!apiKey)
    throw new Error("OpenRouter API key is missing. Please set it in the plugin settings.");
  const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${apiKey}`,
      "HTTP-Referer": "https://obsidian.md"
      // Required by OpenRouter sometimes
    },
    body: JSON.stringify({
      model,
      messages,
      stream: true
    })
  });
  yield* parseSSE(response);
}
async function* parseSSE(response) {
  var _a, _b, _c, _d;
  if (!response.ok) {
    const text = await response.text();
    throw new Error(`HTTP Error ${response.status}: ${text}`);
  }
  const reader = (_a = response.body) == null ? void 0 : _a.getReader();
  const decoder = new TextDecoder();
  if (!reader)
    throw new Error("Could not read response stream");
  while (true) {
    const { done, value } = await reader.read();
    if (done)
      break;
    const chunk = decoder.decode(value, { stream: true });
    const lines = chunk.split("\n");
    for (const line of lines) {
      if (line.trim().startsWith("data: ")) {
        const data = line.trim().slice(6);
        if (data === "[DONE]")
          continue;
        try {
          const parsed = JSON.parse(data);
          if ((_d = (_c = (_b = parsed.choices) == null ? void 0 : _b[0]) == null ? void 0 : _c.delta) == null ? void 0 : _d.content) {
            yield parsed.choices[0].delta.content;
          }
        } catch (e) {
        }
      }
    }
  }
}
async function* streamGemini(messages, apiKey, model) {
  var _a, _b, _c, _d, _e, _f;
  if (!apiKey)
    throw new Error("Gemini API key is missing. Please set it in the plugin settings.");
  const systemMessage = messages.find((m) => m.role === "system");
  const standardMessages = messages.filter((m) => m.role !== "system");
  const contents = standardMessages.map((msg) => ({
    role: msg.role === "assistant" ? "model" : "user",
    parts: [{ text: msg.content }]
  }));
  const body = { contents };
  if (systemMessage) {
    body.systemInstruction = {
      parts: [{ text: systemMessage.content }]
    };
  }
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:streamGenerateContent?alt=sse&key=${apiKey}`;
  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify(body)
  });
  if (!response.ok) {
    const text = await response.text();
    throw new Error(`HTTP Error ${response.status}: ${text}`);
  }
  const reader = (_a = response.body) == null ? void 0 : _a.getReader();
  const decoder = new TextDecoder();
  if (!reader)
    throw new Error("Could not read response stream");
  while (true) {
    const { done, value } = await reader.read();
    if (done)
      break;
    const chunk = decoder.decode(value, { stream: true });
    const lines = chunk.split("\n");
    for (const line of lines) {
      if (line.trim().startsWith("data: ")) {
        const data = line.trim().slice(6);
        if (data === "[DONE]")
          continue;
        try {
          const parsed = JSON.parse(data);
          if ((_f = (_e = (_d = (_c = (_b = parsed.candidates) == null ? void 0 : _b[0]) == null ? void 0 : _c.content) == null ? void 0 : _d.parts) == null ? void 0 : _e[0]) == null ? void 0 : _f.text) {
            yield parsed.candidates[0].content.parts[0].text;
          }
        } catch (e) {
        }
      }
    }
  }
}

// src/ImproveSentenceView.ts
var IMPROVE_SENTENCE_VIEW_TYPE = "improve-sentence-view";
var ImproveSentenceView = class extends import_obsidian2.ItemView {
  constructor(leaf) {
    super(leaf);
    this.messages = [];
    this.selectedSuggestionIndex = -1;
  }
  getViewType() {
    return IMPROVE_SENTENCE_VIEW_TYPE;
  }
  getDisplayText() {
    return "Improve Sentence Chat";
  }
  getIcon() {
    return "message-square";
  }
  async onOpen() {
    var _a;
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("improve-sentence-view-container");
    const header = contentEl.createDiv({ cls: "sidebar-header" });
    header.createEl("h4", { text: "AI Chat" });
    const refreshBtn = header.createDiv({ cls: "refresh-icon" });
    (0, import_obsidian2.setIcon)(refreshBtn, "rotate-ccw");
    refreshBtn.setAttribute("aria-label", "Clear history");
    refreshBtn.addEventListener("click", () => this.clearHistory());
    this.chatContainer = contentEl.createDiv({ cls: "chat-container sidebar" });
    this.chatContainer.addEventListener("contextmenu", (e) => {
      var _a2;
      const selection = (_a2 = window.getSelection()) == null ? void 0 : _a2.toString().trim();
      if (selection) {
        const menu = new import_obsidian2.Menu();
        menu.addItem((item) => {
          item.setTitle("Save to Vocabulary").setIcon("book-marked").onClick(async () => {
            this.plugin.saveVocabulary(selection);
          });
        });
        menu.showAtMouseEvent(e);
      }
    });
    const inputContainer = contentEl.createDiv({ cls: "chat-input-container sidebar" });
    this.suggestionContainer = inputContainer.createDiv({ cls: "slash-suggestions", attr: { style: "display: none;" } });
    this.inputEl = inputContainer.createEl("textarea", { cls: "chat-input" });
    this.inputEl.placeholder = "Type / for commands...";
    this.inputEl.rows = 2;
    this.sendButton = inputContainer.createEl("button", { text: "Send", cls: "chat-send-btn" });
    this.sendButton.addEventListener("click", () => this.sendMessage());
    this.inputEl.addEventListener("keydown", (e) => {
      if (this.suggestionContainer.style.display !== "none") {
        if (e.key === "ArrowDown") {
          e.preventDefault();
          this.navigateSuggestions(1);
        } else if (e.key === "ArrowUp") {
          e.preventDefault();
          this.navigateSuggestions(-1);
        } else if (e.key === "Enter") {
          e.preventDefault();
          this.applySelectedSuggestion();
        } else if (e.key === "Escape") {
          this.hideSuggestions();
        }
        return;
      }
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.sendMessage();
      }
    });
    this.inputEl.addEventListener("input", () => {
      const value = this.inputEl.value;
      if (value.startsWith("/")) {
        this.showSuggestions(value.substring(1));
      } else {
        this.hideSuggestions();
      }
    });
    if (this.messages.length === 0) {
      this.messages.push({ role: "system", content: ((_a = this.plugin.settings.customPrompts[0]) == null ? void 0 : _a.prompt) || "" });
    }
  }
  showSuggestions(query) {
    const customPrompts = this.plugin.settings.customPrompts.filter(
      (p) => p.name.toLowerCase().includes(query.toLowerCase())
    );
    const buildInSuggestions = [
      { id: "test-vocab", name: "Test Recent Vocabulary", prompt: "AI helps you learn and test the 10 most recent words." }
    ].filter((s) => s.name.toLowerCase().includes(query.toLowerCase()));
    const allSuggestions = [...customPrompts, ...buildInSuggestions];
    if (allSuggestions.length === 0) {
      this.hideSuggestions();
      return;
    }
    this.suggestionContainer.empty();
    this.suggestionContainer.style.display = "block";
    this.selectedSuggestionIndex = 0;
    allSuggestions.forEach((suggestion, index) => {
      const item = this.suggestionContainer.createDiv({ cls: "slash-suggestion-item" });
      if (index === 0)
        item.addClass("selected");
      item.createSpan({ cls: "slash-suggestion-name", text: suggestion.name });
      item.createSpan({ cls: "slash-suggestion-preview", text: suggestion.prompt.substring(0, 60) + (suggestion.prompt.length > 60 ? "..." : "") });
      item.addEventListener("click", () => {
        this.applySuggestion(suggestion);
      });
    });
  }
  hideSuggestions() {
    this.suggestionContainer.style.display = "none";
    this.selectedSuggestionIndex = -1;
  }
  navigateSuggestions(direction) {
    var _a;
    const items = this.suggestionContainer.querySelectorAll(".slash-suggestion-item");
    if (items.length === 0)
      return;
    (_a = items[this.selectedSuggestionIndex]) == null ? void 0 : _a.removeClass("selected");
    this.selectedSuggestionIndex = (this.selectedSuggestionIndex + direction + items.length) % items.length;
    const selected = items[this.selectedSuggestionIndex];
    selected.addClass("selected");
    selected.scrollIntoView({ block: "nearest" });
  }
  applySelectedSuggestion() {
    var _a, _b;
    const items = this.suggestionContainer.querySelectorAll(".slash-suggestion-item");
    const selectedLabel = (_b = (_a = items[this.selectedSuggestionIndex]) == null ? void 0 : _a.querySelector(".slash-suggestion-name")) == null ? void 0 : _b.textContent;
    if (!selectedLabel)
      return;
    if (selectedLabel === "Test Recent Vocabulary") {
      this.applySuggestion({ id: "test-vocab", name: "Test Recent Vocabulary" });
    } else {
      const prompt = this.plugin.settings.customPrompts.find((p) => p.name === selectedLabel);
      if (prompt)
        this.applySuggestion(prompt);
    }
  }
  applySuggestion(suggestion) {
    if (suggestion.id === "test-vocab") {
      this.hideSuggestions();
      this.inputEl.value = "";
      this.plugin.testRecentVocabulary();
    } else {
      this.inputEl.value = `/${suggestion.name} `;
      this.hideSuggestions();
      this.inputEl.focus();
    }
  }
  async sendMessage() {
    var _a;
    let text = this.inputEl.value.trim();
    if (!text)
      return;
    this.inputEl.value = "";
    let usedPrompt = ((_a = this.plugin.settings.customPrompts[0]) == null ? void 0 : _a.prompt) || "";
    for (const prompt of this.plugin.settings.customPrompts) {
      const cmd = `/${prompt.name}`;
      if (text.startsWith(cmd)) {
        usedPrompt = prompt.prompt;
        text = text.substring(cmd.length).trim();
        this.messages = [{ role: "system", content: usedPrompt }];
        this.chatContainer.empty();
        break;
      }
    }
    if (!text)
      return;
    this.messages.push({ role: "user", content: text });
    this.renderUserMessage(text);
    await this.generateAssistantResponse();
  }
  async generateAssistantResponse() {
    const assistantMessageIdx = this.messages.length;
    this.messages.push({ role: "assistant", content: "" });
    const bubble = this.createMessageBubble("assistant");
    this.inputEl.disabled = true;
    this.sendButton.disabled = true;
    try {
      const stream = streamAIResponse(this.messages.slice(0, -1), this.plugin.settings);
      let content = "";
      for await (const chunk of stream) {
        content += chunk;
        bubble.innerText = content;
        this.chatContainer.scrollTop = this.chatContainer.scrollHeight;
      }
      this.messages[assistantMessageIdx].content = content;
      bubble.empty();
      await this.parseAndRenderInteractiveComponents(content, bubble);
    } catch (e) {
      bubble.innerText += `
Error: ${e.toString()}`;
    } finally {
      this.inputEl.disabled = false;
      this.sendButton.disabled = false;
      this.inputEl.focus();
      this.chatContainer.scrollTop = this.chatContainer.scrollHeight;
    }
  }
  normalizeAnswer(str) {
    return str.toLowerCase().replace(/[.,/#!$%^&*;:{}=\-_`~()]/g, "").replace(/\s{2,}/g, " ").trim();
  }
  async parseAndRenderInteractiveComponents(content, container) {
    const taggedRegex = /```json:(flashcards|quiz|assessment|choice|scramble)\s*([\s\S]*?)\s*```/g;
    const untaggedRegex = /```(?:json)?\s*([\s\S]*?)\s*```/g;
    let lastIndex = 0;
    let matchFound = false;
    let match;
    const processedMatches = [];
    while ((match = taggedRegex.exec(content)) !== null) {
      matchFound = true;
      processedMatches.push({ start: match.index, end: match.index + match[0].length });
      const textBefore = content.substring(lastIndex, match.index);
      if (textBefore.trim()) {
        const textDiv = container.createDiv();
        await import_obsidian2.MarkdownRenderer.renderMarkdown(textBefore, textDiv, "", this.plugin);
      }
      this.renderComponentByType(match[1], match[2], container);
      lastIndex = match.index + match[0].length;
    }
    if (!matchFound) {
      while ((match = untaggedRegex.exec(content)) !== null) {
        const inner = match[1].trim();
        const type = this.autodetectJsonType(inner);
        if (type) {
          matchFound = true;
          processedMatches.push({ start: match.index, end: match.index + match[0].length });
          const textBefore = content.substring(lastIndex, match.index);
          if (textBefore.trim()) {
            const textDiv = container.createDiv();
            await import_obsidian2.MarkdownRenderer.renderMarkdown(textBefore, textDiv, "", this.plugin);
          }
          this.renderComponentByType(type, inner, container);
          lastIndex = match.index + match[0].length;
        }
      }
    }
    if (!matchFound) {
      const rawJsonRegex = /\{(?:[^{}]|\{[^{}]*\})*\}/g;
      while ((match = rawJsonRegex.exec(content)) !== null) {
        const type = this.autodetectJsonType(match[0]);
        if (type) {
          matchFound = true;
          const textBefore = content.substring(lastIndex, match.index);
          if (textBefore.trim()) {
            const textDiv = container.createDiv();
            await import_obsidian2.MarkdownRenderer.renderMarkdown(textBefore, textDiv, "", this.plugin);
          }
          this.renderComponentByType(type, match[0], container);
          lastIndex = match.index + match[0].length;
        }
      }
    }
    const remainingText = content.substring(lastIndex);
    if (remainingText.trim()) {
      const textDiv = container.createDiv();
      await import_obsidian2.MarkdownRenderer.renderMarkdown(remainingText, textDiv, "", this.plugin);
    }
  }
  autodetectJsonType(jsonStr) {
    try {
      const data = JSON.parse(jsonStr);
      if (data.items && Array.isArray(data.items))
        return "flashcards";
      if (data.questions && Array.isArray(data.questions)) {
        if (data.questions.length > 0 && data.questions[0].options)
          return "choice";
        return "quiz";
      }
      if (data.results && Array.isArray(data.results))
        return "assessment";
      if (data.tasks && Array.isArray(data.tasks))
        return "scramble";
    } catch (e) {
      const lower = jsonStr.toLowerCase();
      if (lower.includes("items") && lower.includes("["))
        return "flashcards";
      if (lower.includes("options") && lower.includes("questions"))
        return "choice";
      if (lower.includes("questions") && lower.includes("["))
        return "quiz";
      if (lower.includes("results") && lower.includes("["))
        return "assessment";
      if (lower.includes("tasks") && lower.includes("scrambled"))
        return "scramble";
    }
    return null;
  }
  renderComponentByType(type, jsonData, container) {
    try {
      this.renderWithParsedData(type, JSON.parse(jsonData), container);
    } catch (e) {
      console.warn(`JSON.parse failed for ${type}, attempting regex extraction fallback...`);
      if (type === "flashcards") {
        const items = this.tryExtractFlashcards(jsonData);
        if (items.length > 0)
          this.renderFlashcards({ items }, container);
        else
          container.createEl("pre", { text: jsonData });
      } else if (type === "quiz") {
        const questions = this.tryExtractQuiz(jsonData);
        if (questions.length > 0)
          this.renderQuiz({ questions }, container);
        else
          container.createEl("pre", { text: jsonData });
      } else if (type === "assessment") {
        const results = this.tryExtractAssessment(jsonData);
        if (results.length > 0)
          this.renderAssessment({ results }, container);
        else
          container.createEl("pre", { text: jsonData });
      } else if (type === "choice") {
        const questions = this.tryExtractChoice(jsonData);
        if (questions.length > 0)
          this.renderChoice({ questions }, container);
        else
          container.createEl("pre", { text: jsonData });
      } else if (type === "scramble") {
        const tasks = this.tryExtractScramble(jsonData);
        if (tasks.length > 0)
          this.renderScramble({ tasks }, container);
        else
          container.createEl("pre", { text: jsonData });
      }
    }
  }
  renderWithParsedData(type, data, container) {
    if (type === "flashcards")
      this.renderFlashcards(data, container);
    else if (type === "quiz")
      this.renderQuiz(data, container);
    else if (type === "assessment")
      this.renderAssessment(data, container);
    else if (type === "choice")
      this.renderChoice(data, container);
    else if (type === "scramble")
      this.renderScramble(data, container);
  }
  renderChoice(data, container) {
    const choiceWrapper = container.createDiv({ cls: "choice-container" });
    const answers = {};
    data.questions.forEach((q, idx) => {
      const questionDiv = choiceWrapper.createDiv({ cls: "choice-question" });
      questionDiv.createEl("div", { cls: "choice-definition", text: q.definition });
      const optionsWrapper = questionDiv.createDiv({ cls: "choice-options" });
      q.options.forEach((opt) => {
        const optBtn = optionsWrapper.createEl("button", { text: opt, cls: "choice-opt-btn" });
        optBtn.addEventListener("click", () => {
          answers[idx] = opt;
          optionsWrapper.querySelectorAll(".choice-opt-btn").forEach((b) => b.removeClass("selected"));
          optBtn.addClass("selected");
        });
      });
    });
    const submitBtn = choiceWrapper.createEl("button", { text: "Check Answers", cls: "quiz-submit-btn" });
    submitBtn.addEventListener("click", () => {
      let userResponse = "Here are my answers for the Multiple Choice quiz:\n";
      data.questions.forEach((q, idx) => {
        const userAnswer = answers[idx] || "(no answer selected)";
        const isCorrect = this.normalizeAnswer(userAnswer) === this.normalizeAnswer(q.answer);
        const questionDiv = choiceWrapper.querySelectorAll(".choice-question")[idx];
        const btns = questionDiv.querySelectorAll(".choice-opt-btn");
        btns.forEach((btn) => {
          const b = btn;
          if (this.normalizeAnswer(b.innerText) === this.normalizeAnswer(q.answer))
            b.addClass("correct");
          else if (b.hasClass("selected"))
            b.addClass("wrong");
        });
        this.plugin.updateSRSProgress(q.answer, isCorrect ? 5 : 1);
        userResponse += `- Problem ${idx + 1} (Definition: ${q.definition.substring(0, 40)}...): I chose "${userAnswer}". (${isCorrect ? "Correct" : "Incorrect, the right word was " + q.answer})
`;
      });
      submitBtn.disabled = true;
      submitBtn.setText("Checked!");
      this.inputEl.value = userResponse + "\nPlease provide brief explanations for these answers.";
      this.sendMessage();
    });
  }
  renderScramble(data, container) {
    const scrambleWrapper = container.createDiv({ cls: "scramble-container" });
    const answers = {};
    data.tasks.forEach((task, idx) => {
      const taskDiv = scrambleWrapper.createDiv({ cls: "scramble-task" });
      const words = typeof task.scrambled === "string" ? task.scrambled.split(" ") : task.scrambled;
      const currentOrder = [...words].sort(() => Math.random() - 0.5);
      const userOrder = [];
      answers[idx] = userOrder;
      const poolDiv = taskDiv.createDiv({ cls: "scramble-pool" });
      const resultDiv = taskDiv.createDiv({ cls: "scramble-result" });
      const renderPool = () => {
        poolDiv.empty();
        currentOrder.forEach((word) => {
          const chip = poolDiv.createSpan({ text: word, cls: "scramble-chip" });
          chip.addEventListener("click", () => {
            userOrder.push(word);
            currentOrder.splice(currentOrder.indexOf(word), 1);
            renderPool();
            renderResult();
          });
        });
      };
      const renderResult = () => {
        resultDiv.empty();
        userOrder.forEach((word) => {
          const chip = resultDiv.createSpan({ text: word, cls: "scramble-chip selected" });
          chip.addEventListener("click", () => {
            currentOrder.push(word);
            userOrder.splice(userOrder.indexOf(word), 1);
            renderPool();
            renderResult();
          });
        });
      };
      renderPool();
      renderResult();
    });
    const submitBtn = scrambleWrapper.createEl("button", { text: "Check Answers", cls: "quiz-submit-btn" });
    submitBtn.addEventListener("click", () => {
      let userResponse = "Here are my answers for the Sentence Scramble:\n";
      data.tasks.forEach((task, idx) => {
        const userAnswer = (answers[idx] || []).join(" ");
        const isCorrect = this.normalizeAnswer(userAnswer) === this.normalizeAnswer(task.original);
        const taskDiv = scrambleWrapper.querySelectorAll(".scramble-task")[idx];
        taskDiv.removeClass("correct");
        taskDiv.removeClass("wrong");
        taskDiv.addClass(isCorrect ? "correct" : "wrong");
        this.plugin.updateSRSProgress(task.word, isCorrect ? 5 : 1);
        userResponse += `- Task ${idx + 1} (${task.word}): I ordered it as "${userAnswer}". (${isCorrect ? "Correct" : "Incorrect, it should be " + task.original})
`;
      });
      submitBtn.disabled = true;
      submitBtn.setText("Checked!");
      this.inputEl.value = userResponse + "\nPlease provide brief explanations for these constructions.";
      this.sendMessage();
    });
  }
  tryExtractChoice(str) {
    const questions = [];
    const qRegex = /\{[\s\S]*?definition["'\s:]+([^"'\n]*)["']?[\s\S]*?answer["'\s:]+([^"'\n]*)["']?[\s\S]*?options["'\s:]+\[([^\]]*)\][\s\S]*?\}/gi;
    let match;
    while ((match = qRegex.exec(str)) !== null) {
      const options = match[3].split(",").map((o) => o.replace(/^[":\s]+|[":\s]+$/g, "").trim());
      questions.push({
        definition: match[1].replace(/^[":\s]+/, "").trim(),
        answer: match[2].replace(/^[":\s]+/, "").trim(),
        options
      });
    }
    return questions;
  }
  tryExtractScramble(str) {
    const tasks = [];
    const tRegex = /\{[\s\S]*?scrambled["'\s:]+([^"'\n\r\[]*)[\s\S]*?original["'\s:]+([^"'\n]*)["']?[\s\S]*?(?:word["'\s:]+([^"'\n]*)["']?)?[\s\S]*?\}/gi;
    let match;
    while ((match = tRegex.exec(str)) !== null) {
      tasks.push({
        scrambled: match[1].replace(/^[":\s]+/, "").trim(),
        original: match[2].replace(/^[":\s]+/, "").trim(),
        word: (match[3] || "").replace(/^[":\s]+/, "").trim()
      });
    }
    return tasks;
  }
  tryExtractFlashcards(str) {
    const items = [];
    const itemRegex = /\{[\s\S]*?word["'\s:]+([^"'\n]*)["']?[\s\S]*?definition["'\s:]+([^"'\n]*)["']?(?:[\s\S]*?example["'\s:]+([^"'\n]*)["']?)?[\s\S]*?\}/gi;
    let match;
    while ((match = itemRegex.exec(str)) !== null) {
      if (match[1].trim() || match[2].trim()) {
        items.push({
          word: match[1].replace(/^[":\s]+/, "").trim(),
          definition: match[2].replace(/^[":\s]+/, "").trim(),
          example: (match[3] || "").replace(/^[":\s]+/, "").trim()
        });
      }
    }
    return items;
  }
  tryExtractQuiz(str) {
    const questions = [];
    const questionRegex = /\{[\s\S]*?sentence["'\s:]+([^"'\n]*)["']?[\s\S]*?answer["'\s:]+([^"'\n]*)["']?[\s\S]*?word["'\s:]+([^"'\n]*)["']?[\s\S]*?\}/gi;
    let match;
    while ((match = questionRegex.exec(str)) !== null) {
      questions.push({
        sentence: match[1].replace(/^[":\s]+/, "").trim(),
        answer: match[2].replace(/^[":\s]+/, "").trim(),
        word: match[3].replace(/^[":\s]+/, "").trim()
      });
    }
    return questions;
  }
  tryExtractAssessment(str) {
    const results = [];
    const resultRegex = /\{[\s\S]*?word["'\s:]+([^"'\n]*)["']?[\s\S]*?score["'\s:]+(\d+)[\s\S]*?\}/gi;
    let match;
    while ((match = resultRegex.exec(str)) !== null) {
      results.push({
        word: match[1].replace(/^[":\s]+/, "").trim(),
        score: parseInt(match[2])
      });
    }
    return results;
  }
  cleanJson(str) {
    return str.replace(/,\s*([}\]])/g, "$1").replace(/(['"])?([a-zA-Z0-9_]+)(['"])?:/g, '"$2":');
  }
  renderFlashcards(data, container) {
    const flashcardWrapper = container.createDiv({ cls: "flashcard-container" });
    data.items.forEach((item) => {
      const card = flashcardWrapper.createDiv({ cls: "flashcard" });
      const front = card.createDiv({ cls: "flashcard-front", text: item.word });
      const back = card.createDiv({ cls: "flashcard-back" });
      back.createEl("div", { cls: "flashcard-definition", text: item.definition });
      if (item.example) {
        back.createEl("div", { cls: "flashcard-example", text: `Ex: ${item.example}` });
      }
      card.addEventListener("click", () => {
        card.toggleClass("flipped", !card.hasClass("flipped"));
      });
    });
  }
  renderQuiz(data, container) {
    const quizWrapper = container.createDiv({ cls: "quiz-container" });
    const answers = {};
    data.questions.forEach((q, idx) => {
      const questionDiv = quizWrapper.createDiv({ cls: "quiz-question" });
      const parts = q.sentence.split(/\[blank\]|_{3,}/g);
      const sentenceEl = questionDiv.createEl("div", { cls: "quiz-sentence" });
      parts.forEach((part, pIdx) => {
        sentenceEl.createSpan({ text: part });
        if (pIdx < parts.length - 1) {
          const input = sentenceEl.createEl("input", { type: "text", cls: "quiz-input", placeholder: "..." });
          input.addEventListener("change", () => {
            answers[idx] = input.value.trim();
          });
          input.addEventListener("keydown", (e) => {
            e.stopPropagation();
          });
          input.addEventListener("click", (e) => {
            e.stopPropagation();
            input.focus();
          });
        }
      });
      if (q.choices && q.choices.length > 0) {
        const choiceWrapper = questionDiv.createDiv({ cls: "quiz-choices" });
        q.choices.forEach((choice) => {
          const btn = choiceWrapper.createEl("button", { text: choice, cls: "quiz-choice-btn" });
          btn.addEventListener("click", () => {
            const input = questionDiv.querySelector(".quiz-input");
            if (input) {
              input.value = choice;
              answers[idx] = choice;
            }
            choiceWrapper.querySelectorAll(".quiz-choice-btn").forEach((b) => b.removeClass("selected"));
            btn.addClass("selected");
          });
        });
      }
    });
    const submitBtn = quizWrapper.createEl("button", { text: "Check Answers", cls: "quiz-submit-btn" });
    submitBtn.addEventListener("click", async () => {
      let userResponse = "Here are my answers for the quiz (I've already highlighted them in the UI):\n";
      data.questions.forEach((q, idx) => {
        const userAnswer = (answers[idx] || "").trim();
        const isCorrect = this.normalizeAnswer(userAnswer) === this.normalizeAnswer(q.answer);
        const questionEl = quizWrapper.querySelectorAll(`.quiz-question`)[idx];
        const inputs = questionEl.querySelectorAll(".quiz-input");
        inputs.forEach((input) => {
          input.removeClass("correct");
          input.removeClass("wrong");
          input.addClass(isCorrect ? "correct" : "wrong");
        });
        this.plugin.updateSRSProgress(q.word, isCorrect ? 5 : 1);
        userResponse += `- Question ${idx + 1} (${q.word}): My answer was "${userAnswer}". (${isCorrect ? "Correct" : "Incorrect, the right answer is " + q.answer})
`;
      });
      submitBtn.disabled = true;
      submitBtn.setText("Checked!");
      this.inputEl.value = userResponse + "\nPlease provide brief explanations for these answers.";
      this.sendMessage();
    });
  }
  renderAssessment(data, container) {
    const assessmentDiv = container.createDiv({ cls: "assessment-result" });
    assessmentDiv.createEl("h4", { text: "Practice Session Complete!" });
    data.results.forEach((res) => {
      const itemDiv = assessmentDiv.createDiv({ cls: "assessment-item" });
      itemDiv.createSpan({ text: res.word, cls: "assessment-word" });
      itemDiv.createSpan({ text: ` Score: ${res.score}/5`, cls: `assessment-score q${res.score}` });
      this.plugin.updateSRSProgress(res.word, res.score);
    });
  }
  renderUserMessage(content) {
    const bubble = this.createMessageBubble("user");
    bubble.innerText = content;
    this.chatContainer.scrollTop = this.chatContainer.scrollHeight;
  }
  createMessageBubble(role) {
    const wrapper = this.chatContainer.createDiv({ cls: `chat-message ${role}` });
    const bubble = wrapper.createDiv({ cls: "bubble" });
    return bubble;
  }
  async clearHistory() {
    var _a;
    this.messages = [];
    this.messages.push({ role: "system", content: ((_a = this.plugin.settings.customPrompts[0]) == null ? void 0 : _a.prompt) || "" });
    this.chatContainer.empty();
  }
  async setMessages(messages) {
    this.messages = [...messages];
    this.chatContainer.empty();
    for (const msg of this.messages) {
      if (msg.role === "system")
        continue;
      const bubble = this.createMessageBubble(msg.role);
      await import_obsidian2.MarkdownRenderer.renderMarkdown(msg.content, bubble, "", this.plugin);
    }
    this.chatContainer.scrollTop = this.chatContainer.scrollHeight;
  }
  async startImprovement(sentence, promptContent) {
    var _a;
    this.messages = [];
    const systemPrompt = promptContent || ((_a = this.plugin.settings.customPrompts[0]) == null ? void 0 : _a.prompt) || "";
    this.messages.push({ role: "system", content: systemPrompt });
    this.messages.push({ role: "user", content: sentence });
    this.chatContainer.empty();
    this.renderUserMessage(sentence);
    await this.generateAssistantResponse();
  }
};

// src/main.ts
var ImproveYourSentencePlugin = class extends import_obsidian3.Plugin {
  async onload() {
    console.log("loading improve your sentence plugin");
    await this.loadSettings();
    this.registerView(
      IMPROVE_SENTENCE_VIEW_TYPE,
      (leaf) => {
        const view = new ImproveSentenceView(leaf);
        view.plugin = this;
        return view;
      }
    );
    this.addRibbonIcon("message-square", "Open Improve Sentence Chat", () => {
      this.activateView();
    });
    this.registerCustomCommands();
    this.addCommand({
      id: "open-improve-sentence-sidebar",
      name: "Open Sidebar Chat",
      callback: () => {
        this.activateView();
      }
    });
    this.addCommand({
      id: "save-selected-vocabulary",
      name: "Save Selected to Vocabulary",
      editorCallback: (editor) => {
        const selection = editor.getSelection().trim();
        if (selection) {
          this.saveVocabulary(selection);
        }
      }
    });
    this.addCommand({
      id: "test-recent-vocabulary",
      name: "AI Test Recent Vocabulary",
      callback: () => {
        this.testRecentVocabulary();
      }
    });
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, view) => {
        const selection = editor.getSelection().trim();
        if (selection) {
          menu.addItem((item) => {
            item.setTitle("Save to Vocabulary").setIcon("book-marked").onClick(async () => {
              this.saveVocabulary(selection);
            });
          });
        }
      })
    );
    this.addSettingTab(new ImproveYourSentenceSettingTab(this.app, this));
  }
  async saveVocabulary(word, context) {
    const existing = this.settings.vocabulary.find((v) => v.word.toLowerCase() === word.toLowerCase());
    if (existing) {
      console.log("Word already in vocabulary");
      return;
    }
    const newItem = {
      word,
      context,
      dateAdded: Date.now(),
      nextReview: Date.now() + 24 * 60 * 60 * 1e3,
      // Review in 1 day
      interval: 1,
      repetition: 1,
      efactor: 2.5
    };
    this.settings.vocabulary.push(newItem);
    await this.saveSettings();
    new import_obsidian3.Notice(`Saved "${word}" to vocabulary.`);
  }
  async testRecentVocabulary() {
    const now = Date.now();
    const words = this.settings.vocabulary.sort((a, b) => a.nextReview - b.nextReview).slice(0, 10);
    if (words.length === 0) {
      new import_obsidian3.Notice("No vocabulary words saved yet.");
      return;
    }
    const wordList = words.map((v) => v.word).join(", ");
    const prompt = `You are a Vocabulary Mentor helping me master these 10 words: ${wordList}.
Always guide me through these steps sequentially. Start with Step 1: Flashcards.

IMPORTANT: You MUST ONLY output the JSON data inside the specific markdown code blocks as shown below. Do not include extra text or ignore the block format.

1. **Flashcards**: Provide definitions and example sentences for each word.
   \`\`\`json:flashcards
   {
     "items": [
       { "word": "word1", "definition": "...", "example": "..." },
       ...
     ]
   }
   \`\`\`
2. **Exercise**: Create interactive exercises for each word. You can choose from:
   - **Fill in the Blank**:
     \`\`\`json:quiz
     { "questions": [{ "sentence": "He was [blank].", "answer": "happy", "word": "happy" }] }
     \`\`\`
   - **Multiple Choice**:
     \`\`\`json:choice
     { "questions": [{ "definition": "Feeling pleasure.", "answer": "happy", "options": ["happy", "sad", "angry", "tired"] }] }
     \`\`\`
   - **Sentence Scramble**:
     \`\`\`json:scramble
     { "tasks": [{ "scrambled": "is He happy today", "original": "He is happy today", "word": "happy" }] }
     \`\`\`

ALWAYS include the code blocks exactly as defined above so the plugin can render the interactive UI. After providing the exercises, wait for me to check my answers. When I send you my answers, provide the correct answers and a brief explanation for each one to help me learn from my mistakes. (Note: The plugin handles the SRS progress automatically, so you don't need to provide scores).`;
    const view = await this.activateView();
    if (view) {
      view.startImprovement("Vocabulary Practice Session", prompt);
    }
  }
  async updateSRSProgress(word, quality) {
    const item = this.settings.vocabulary.find((v) => v.word.toLowerCase() === word.toLowerCase());
    if (!item)
      return;
    if (quality >= 3) {
      if (item.repetition === 0) {
        item.interval = 1;
      } else if (item.repetition === 1) {
        item.interval = 6;
      } else {
        item.interval = Math.round(item.interval * item.efactor);
      }
      item.repetition++;
    } else {
      item.repetition = 0;
      item.interval = 1;
    }
    item.efactor = item.efactor + (0.1 - (5 - quality) * (0.08 + (5 - quality) * 0.02));
    if (item.efactor < 1.3)
      item.efactor = 1.3;
    item.nextReview = Date.now() + item.interval * 24 * 60 * 60 * 1e3;
    await this.saveSettings();
    console.log(`Updated SRS for ${word}: Interval=${item.interval}, Repetition=${item.repetition}, E-Factor=${item.efactor.toFixed(2)}, Next Review=${new Date(item.nextReview).toLocaleDateString()}`);
  }
  registerCustomCommands() {
    this.settings.customPrompts.forEach((prompt) => {
      this.addCommand({
        id: `prompt-${prompt.id}`,
        name: `Prompt: ${prompt.name}`,
        editorCallback: (editor) => {
          const selection = editor.getSelection();
          if (selection.trim() === "") {
            return;
          }
          this.activateView().then((v) => {
            if (v) {
              v.startImprovement(selection, prompt.prompt);
            }
          });
        }
      });
    });
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(IMPROVE_SENTENCE_VIEW_TYPE)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (!rightLeaf)
        return null;
      leaf = rightLeaf;
      await leaf.setViewState({
        type: IMPROVE_SENTENCE_VIEW_TYPE,
        active: true
      });
    }
    workspace.revealLeaf(leaf);
    return leaf.view;
  }
  onunload() {
    console.log("unloading improve your sentence plugin");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
